# Generated by Django 4.0 on 2024-03-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_project_options_alter_projectphoto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
