# Generated by Django 4.0 on 2024-04-03 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_project_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_object_name', models.CharField(max_length=255)),
                ('project_completed', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Объект проектирования',
                'verbose_name_plural': 'Объекты проектирования',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_task', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('application_completed', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('design_objects', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='main.design_object')),
            ],
            options={
                'verbose_name': 'Пятно',
                'verbose_name_plural': 'Пятна',
            },
        ),
        migrations.RemoveField(
            model_name='projectphoto',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectPhoto',
        ),
        migrations.AddField(
            model_name='design_object',
            name='tasks',
            field=models.ManyToManyField(to='main.Task'),
        ),
    ]
