# Generated by Django 4.0 on 2024-04-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_design_object_task_title_remove_projectphoto_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design_object',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='design_objects_type',
            field=models.ManyToManyField(to='main.Design_object'),
        ),
        migrations.AlterField(
            model_name='task',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
