# Generated by Django 4.0 on 2024-04-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.CharField(max_length=255)),
                ('design_objects', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spots', to='main.design_object')),
            ],
            options={
                'verbose_name': 'Пятно',
                'verbose_name_plural': 'Пятна',
            },
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
