# Generated by Django 4.0 on 2024-04-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_spot_delete_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
