# Generated by Django 4.0 on 2024-04-18 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterField(
            model_name='spot',
            name='design_objects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='main.design_object'),
        ),
    ]
